"""main_ha_version: what the declared main Home Assistant cannot parse is left out of discovery.

The main HA rejects the WHOLE device payload over one unknown platform or one unknown device class, so an entity
carrying `radon` (a device class of 2026.8) or a `date` entity (an MQTT platform of 2026.5) takes every other entity
of its device down with it on an older main HA.  The table (`ha_compat.json`, generated by `tools/gen_ha_compat.py`)
says when each of them appeared; these tests check the table itself, the filtering, the setting and the counters -
and, first of all, that a deployment which does not set it publishes exactly what it published before.
"""

import collections
import json
import os
import tempfile
import time
import unittest
from types import SimpleNamespace
from unittest import mock

from homeassistant.core import State
from homeassistant.helpers import entity_registry as er

from custom_components.integration_manager import discovery as disc
from custom_components.integration_manager import mqtt_publisher as mp
from custom_components.integration_manager.mqtt_rules import MqttRules

BASE = "hass_demo"
PREFIX = BASE + "_"
CMD = f"{BASE}/cmd"

# One entity per thing the filter can do: a device class of 2026.8, an MQTT platform of 2026.5, and two that
# every version in the table knows (the control group: they must come out identical whatever is declared).
STATES = {
    "sensor.radon_level": State("sensor.radon_level", "42",
                                {"device_class": "radon", "unit_of_measurement": "Bq/m³", "state_class": "measurement"}),
    "sensor.meter": State("sensor.meter", "5", {"device_class": "power", "unit_of_measurement": "W"}),
    "date.next_service": State("date.next_service", "2026-10-01", {}),
    "switch.pump": State("switch.pump", "on", {"device_class": "switch"}),
}


def _entry(entity_id):
    """A registry entry that carries nothing of its own: the state's attributes decide, as for a YAML platform."""
    return SimpleNamespace(entity_id=entity_id, domain=entity_id.split(".")[0], platform="demo", device_id=None,
                           disabled_by=None, disabled=False, capabilities=None, unit_of_measurement=None, name=None,
                           original_name=entity_id, icon=None, original_icon=None, entity_category=None,
                           device_class=None, original_device_class=None, unique_id=entity_id, hidden=False,
                           area_id=None, labels=set(), config_entry_id="e1", translation_key=None, options={},
                           supported_features=0)


class Registry:
    def __init__(self, *ids):
        self.entities = {eid: _entry(eid) for eid in ids}

    def async_get(self, entity_id):
        return self.entities.get(entity_id)


class Loop:
    def call_later(self, delay, cb, *args):
        return SimpleNamespace(cancel=lambda: None)

    def call_soon_threadsafe(self, cb, *args):
        cb(*args)


def topic_for(entity_id):
    domain, object_id = entity_id.split(".", 1)
    return f"{BASE}/demo/{domain}/{object_id}"


class _DiscoveryCase(unittest.TestCase):
    """build_component against a registry of the four entities above."""

    def setUp(self):
        self.registry = Registry(*STATES)
        patch = mock.patch.object(er, "async_get", return_value=self.registry)
        patch.start()
        self.addCleanup(patch.stop)

    def component(self, entity_id, version=None):
        """The component of one entity for a declared main HA version (None = the call as it was before the setting)."""
        state = STATES[entity_id]
        if version is None:
            return disc.build_component(mock.Mock(), state, topic_for(entity_id), CMD, PREFIX)
        return disc.build_component(mock.Mock(), state, topic_for(entity_id), CMD, PREFIX, disc.compat_for(version))


class TableTest(unittest.TestCase):
    """The generated table says what the wheels say."""

    def setUp(self):
        self.table = disc.compat_table()

    def test_the_table_is_stamped_with_what_was_scanned(self):
        generated = self.table["generated"]
        self.assertEqual(generated["oldest"], "2025.1")  # below 2024.11 no discovery arrives at all
        self.assertTrue(generated["at"].endswith("Z"), generated["at"])
        self.assertGreaterEqual(len(generated["versions"]), 12)
        self.assertEqual(disc.parse_ha_version(generated["versions"][-1]), disc.parse_ha_version(generated["newest"]))

    def test_the_platforms_that_arrived_in_2026_5(self):
        for platform in ("date", "time", "datetime"):
            self.assertEqual(self.table["platforms"][platform], "2026.5")
        self.assertEqual(self.table["platforms"]["sensor"], "2025.1")  # i.e. at or before the oldest scanned

    def test_radon_arrived_in_2026_8(self):
        self.assertEqual(self.table["device_classes"]["sensor"]["radon"], "2026.8")
        self.assertEqual(self.table["device_classes"]["number"]["radon"], "2026.8")
        self.assertEqual(self.table["device_classes"]["sensor"]["power"], "2025.1")

    def test_every_native_domain_the_translator_uses_is_in_the_table(self):
        self.assertEqual(disc.NATIVE - set(self.table["platforms"]), set())


class VersionTest(unittest.TestCase):
    def test_a_version_is_read_down_to_its_release(self):
        for value, release in (("2026.8", (2026, 8)), ("2026.8.3", (2026, 8)), (" 2026.10.1 ", (2026, 10)),
                               ("2026.9.0b0", (2026, 9))):
            self.assertEqual(disc.parse_ha_version(value), release, value)

    def test_anything_else_is_not_a_version(self):
        for value in ("", "   ", "yesterday", "8.3", "2026", "2026.", "v2026.8", "2026.8.3-dev", None, 2026.8, []):
            self.assertIsNone(disc.parse_ha_version(value), value)

    def test_no_version_and_no_usable_version_filter_nothing(self):
        for value in ("", "   ", "yesterday", None):
            self.assertIsNone(disc.compat_for(value), value)

    def test_a_version_at_or_above_the_newest_scanned_filters_nothing(self):
        newest = disc.compat_table()["generated"]["newest"]
        for value in (newest, f"{newest}.7", "2030.1"):
            self.assertIsNone(disc.compat_for(value), value)

    def test_below_the_table_the_floor_of_the_table_is_used(self):
        self.assertEqual(disc.compat_for("2024.11").release, disc.parse_ha_version("2025.1"))


class UnsetChangesNothingTest(_DiscoveryCase):
    """The promise of the default: a deployment that does not declare a version publishes today's payload."""

    def test_every_component_is_what_it_was_without_the_setting(self):
        for entity_id in STATES:
            with self.subTest(entity=entity_id):
                self.assertEqual(self.component(entity_id, ""), self.component(entity_id))

    def test_the_publisher_builds_the_same_components_with_the_setting_empty(self):
        published = publisher_components("")
        for entity_id in STATES:
            with self.subTest(entity=entity_id):
                self.assertEqual(published[entity_id], self.component(entity_id))

    def test_a_version_newer_than_the_table_changes_nothing_either(self):
        for entity_id in STATES:
            with self.subTest(entity=entity_id):
                self.assertEqual(self.component(entity_id, "2030.1"), self.component(entity_id))


class PlatformFilterTest(_DiscoveryCase):
    """date/time/datetime got their MQTT platforms in 2026.5."""

    def test_2026_4_mirrors_a_date_entity_as_a_sensor(self):
        comp = self.component("date.next_service", "2026.4")
        self.assertEqual(comp["platform"], "sensor")
        self.assertEqual(comp["default_entity_id"], "sensor.date_next_service")
        self.assertEqual(comp["name"], "date.next_service (date)")
        self.assertEqual(comp["state_topic"], topic_for("date.next_service"))  # the entity is still there, read-only
        self.assertNotIn("command_topic", comp)

    def test_2026_5_announces_the_date_platform(self):
        comp = self.component("date.next_service", "2026.5")
        self.assertEqual(comp["platform"], "date")
        self.assertEqual(comp, self.component("date.next_service"))

    def test_a_platform_every_version_has_is_untouched(self):
        for version in ("2025.1", "2026.4", "2026.7"):
            with self.subTest(version=version):
                self.assertEqual(self.component("switch.pump", version)["platform"], "switch")


class DeviceClassFilterTest(_DiscoveryCase):
    """SensorDeviceClass.RADON arrived in 2026.8: on 2026.7 the entity is announced without it."""

    def test_2026_7_drops_radon_but_keeps_the_entity(self):
        old = self.component("sensor.radon_level", "2026.7")
        current = self.component("sensor.radon_level")
        self.assertEqual(current["device_class"], "radon")
        self.assertNotIn("device_class", old)
        self.assertEqual(old["unique_id"], current["unique_id"])
        self.assertEqual(old["state_topic"], current["state_topic"])
        self.assertEqual(old["unit_of_measurement"], "Bq/m³")  # only the class the consumer cannot parse is left out
        self.assertEqual({**old, "device_class": "radon"}, current)

    def test_2026_8_keeps_radon(self):
        self.assertEqual(self.component("sensor.radon_level", "2026.8"), self.component("sensor.radon_level"))

    def test_a_device_class_every_version_has_is_untouched(self):
        for version in ("2025.1", "2026.7"):
            with self.subTest(version=version):
                self.assertEqual(self.component("sensor.meter", version)["device_class"], "power")
                self.assertEqual(self.component("switch.pump", version)["device_class"], "switch")

    def test_a_device_class_no_scanned_version_has_is_left_out(self):
        """It would fail the consumer's enum the same way: dropping it costs one attribute, keeping it the device."""
        state = State("sensor.invented", "1", {"device_class": "nonesuch"})
        comp = disc.build_component(mock.Mock(), state, topic_for("sensor.invented"), CMD, PREFIX,
                                    disc.compat_for("2026.7"))
        self.assertNotIn("device_class", comp)

    def test_a_domain_the_table_knows_no_device_classes_for_is_left_alone(self):
        compat = disc.compat_for("2026.7")
        self.assertNotIn("climate", disc.compat_table()["device_classes"])
        self.assertTrue(compat.knows_device_class("climate", "whatever"))

    def test_a_registry_entry_without_a_state_is_filtered_too(self):
        """Disabled entries are announced from the registry alone, through the same path."""
        entry = _entry("sensor.radon_level")
        entry.device_class = "radon"
        comp = disc.build_component_from_entry(mock.Mock(), entry, topic_for("sensor.radon_level"), CMD, PREFIX,
                                               disc.compat_for("2026.7"))
        self.assertNotIn("device_class", comp)
        self.assertEqual(comp["platform"], "sensor")


def make_publisher(main_ha_version, tmp):
    """A publisher with the four entities above and nothing connected: enough for _group_by_device."""
    pub = mp.MqttPublisher.__new__(mp.MqttPublisher)
    pub.config = mp.MqttConfig(enabled=True, discovery_enabled=True, main_ha_version=main_ha_version)
    pub.path = os.path.join(tmp, "mqtt.json")
    pub._saved = None
    pub._connected, pub._moving, pub._stopping = True, False, False
    pub._live_base, pub._live_prefix, pub._key_provider = BASE, None, lambda: BASE
    pub.rules = MqttRules(os.path.join(tmp, "mqtt_rules.json"))
    pub._collision_warned, pub._default_id_warned, pub._compat_warned = set(), set(), set()
    pub.hass = mock.Mock()
    pub.hass.data = {}
    pub.hass.loop = Loop()
    pub.hass.async_create_task = lambda *a, **k: None
    pub.hass.states.async_all.side_effect = lambda: list(STATES.values())
    pub.hass.states.get.side_effect = STATES.get
    pub.hass.config.components = {"demo"}
    pub.hass.config.config_dir = tmp
    pub.hass.is_running = True
    pub._last_hash, pub._blocks, pub._topics, pub._pending_clears = {}, {}, {}, set()
    pub.stats = collections.defaultdict(int)
    pub._health_last, pub.manager, pub._registry_timer, pub._services_timer = {}, None, None, None
    pub._health_provider = lambda: {"integration": "demo", "state": "ok"}
    pub._rules_provider = lambda domain: {"stale_s": 900, "mode": "periodic", "unavailable_pct": 50}
    pub.history = collections.deque()
    pub._discovery_map, pub._identity_sweep_due, pub._resync_excluded, pub._undiscover_due = {}, False, False, False
    pub._started_at, pub._last_full = time.time(), 0.0
    pub._orphan_sweep_due, pub._boot_removed, pub._boot_components = False, set(), {}
    pub._publish = lambda topic, payload, retain=True, qos=None: True
    return pub


def publisher_components(main_ha_version):
    """{entity_id: component} the publisher would announce for the declared version."""
    tmp = tempfile.mkdtemp()
    pub = make_publisher(main_ha_version, tmp)
    with mock.patch.object(er, "async_get", return_value=Registry(*STATES)), \
            mock.patch.object(mp, "platform_of", return_value="demo"):
        groups, _counts = pub._group_by_device()
    return {eid: comp for _block, comps in groups.values() for eid, comp in comps.items()}


class EntitiesPageAgreesTest(unittest.TestCase):
    """The Entities page marks a date/time/datetime entity as needing a newer main Home Assistant, and the
    mark is gated on the row saying `native`.  With a version declared, those entities are published as
    sensor mirrors instead - so the page has to say `mirror` there, or it would tell the operator to exclude
    an entity the setting has already taken care of."""

    def rows(self, main_ha_version):
        from custom_components.integration_manager import entities_page

        tmp = tempfile.mkdtemp()
        pub = make_publisher(main_ha_version, tmp)
        hass = SimpleNamespace(states=SimpleNamespace(async_all=lambda: list(STATES.values())),
                               data={}, config=SimpleNamespace(config_dir=tmp))
        registry = Registry(*STATES)
        with mock.patch.object(er, "async_get", return_value=registry), \
                mock.patch.object(mp, "platform_of", return_value="demo"), \
                mock.patch.object(entities_page, "platform_of", return_value="demo"):
            return {r["entity_id"]: r for r in entities_page.entity_rows(hass, pub)}

    def test_a_date_entity_reads_native_when_no_version_is_declared(self):
        self.assertEqual(self.rows("")["date.next_service"]["discovery"], "native")

    def test_it_reads_mirror_once_a_version_without_that_platform_is_declared(self):
        self.assertEqual(self.rows("2026.4")["date.next_service"]["discovery"], "mirror")

    def test_an_always_mappable_domain_is_unaffected(self):
        for version in ("", "2026.4"):
            with self.subTest(version=version):
                self.assertEqual(self.rows(version)["sensor.meter"]["discovery"], "native")


class CountersTest(unittest.TestCase):
    """The setting must be visible: GET /api/mqtt/status counts what it left out, next to the other discovery counts."""

    def counts(self, main_ha_version):
        """(status, counters) of one discovery pass for a declared version."""
        tmp = tempfile.mkdtemp()
        pub = make_publisher(main_ha_version, tmp)
        with mock.patch.object(er, "async_get", return_value=Registry(*STATES)), \
                mock.patch.object(mp, "platform_of", return_value="demo"):
            _groups, counts = pub._group_by_device()
            return pub.status(), counts

    def test_nothing_is_counted_when_the_setting_is_empty(self):
        status, counts = self.counts("")
        self.assertEqual((counts["compat_device_classes"], counts["compat_platforms"]), (0, 0))
        self.assertEqual(status["main_ha_version"], "")

    def test_the_counters_rise_with_a_declared_version(self):
        status, counts = self.counts("2026.4")
        self.assertEqual(counts["compat_device_classes"], 1)  # sensor.radon_level
        self.assertEqual(counts["compat_platforms"], 1)       # date.next_service
        self.assertEqual(counts["mirrored"], 1)               # and it is counted as a mirror like any other
        self.assertEqual(status["main_ha_version"], "2026.4")

    def test_only_the_device_class_counts_on_2026_7(self):
        _status, counts = self.counts("2026.7")
        self.assertEqual((counts["compat_device_classes"], counts["compat_platforms"]), (1, 0))

    def test_the_status_carries_the_counts_after_a_discovery_publish(self):
        tmp = tempfile.mkdtemp()
        pub = make_publisher("2026.4", tmp)
        with mock.patch.object(er, "async_get", return_value=Registry(*STATES)), \
                mock.patch.object(mp, "platform_of", return_value="demo"):
            pub._publish_discovery_all(follow_up=False)
            status = pub.status()
        self.assertEqual(status["discovery_compat_device_classes_dropped"], 1)
        self.assertEqual(status["discovery_compat_platforms_mirrored"], 1)
        self.assertEqual(status["main_ha_version"], "2026.4")

    def test_the_counters_exist_before_anything_was_published(self):
        """GET /api/mqtt/status answers from the first second, not only after the first discovery pass."""
        tmp = tempfile.mkdtemp()
        hass = mock.Mock()
        hass.config.path.side_effect = lambda *parts: os.path.join(tmp, *parts)
        os.makedirs(os.path.join(tmp, "integration_manager"), exist_ok=True)
        pub = mp.MqttPublisher(hass)
        for key in ("discovery_compat_device_classes_dropped", "discovery_compat_platforms_mirrored",
                    "discovery_collisions", "discovery_default_id_duplicates"):
            self.assertEqual(pub.stats[key], 0, key)

    def test_each_drop_is_logged_once(self):
        tmp = tempfile.mkdtemp()
        pub = make_publisher("2026.4", tmp)
        with mock.patch.object(er, "async_get", return_value=Registry(*STATES)), \
                mock.patch.object(mp, "platform_of", return_value="demo"):
            with self.assertLogs(mp._LOGGER, level="INFO") as first:
                pub._group_by_device()
            messages = [r.getMessage() for r in first.records]
            self.assertTrue(any("sensor.radon" in m for m in messages), messages)
            self.assertTrue(any("date" in m and "sensors" in m for m in messages), messages)
            with mock.patch.object(mp._LOGGER, "info") as again:
                pub._group_by_device()
            again.assert_not_called()


class SettingTest(unittest.TestCase):
    """The setting itself: default, save, and what a bad value does."""

    def publisher(self):
        return make_publisher("", tempfile.mkdtemp())

    def test_the_default_is_empty(self):
        self.assertEqual(mp.MqttConfig().main_ha_version, "")

    def test_a_version_is_saved_stripped(self):
        pub = self.publisher()
        self.assertEqual(pub._validated({"main_ha_version": "  2026.4  "}).main_ha_version, "2026.4")
        self.assertEqual(pub._validated({"main_ha_version": "2026.8.3"}).main_ha_version, "2026.8.3")
        self.assertEqual(pub._validated({"main_ha_version": ""}).main_ha_version, "")

    def test_the_form_refuses_a_value_that_is_not_a_version(self):
        pub = self.publisher()
        for value in ("yesterday", "2026", "v2026.8", 5):
            with self.subTest(value=value), self.assertRaises(ValueError):
                pub._validated({"main_ha_version": value})

    def test_a_bad_value_on_disk_falls_back_to_the_default_with_a_log_line(self):
        pub = self.publisher()
        with self.assertLogs(mp._LOGGER, level="WARNING") as logs:
            sane = pub._sane({"main_ha_version": "yesterday"})
        self.assertEqual(sane["main_ha_version"], "")
        self.assertTrue(any("main_ha_version" in r.getMessage() for r in logs.records), logs.output)

    def test_a_value_of_the_wrong_type_on_disk_falls_back_too(self):
        pub = self.publisher()
        with self.assertLogs(mp._LOGGER, level="WARNING"):
            self.assertEqual(pub._sane({"main_ha_version": 2026.8})["main_ha_version"], "")

    def test_a_usable_value_on_disk_is_kept(self):
        pub = self.publisher()
        self.assertEqual(pub._sane({"main_ha_version": "2026.4"})["main_ha_version"], "2026.4")

    def test_the_setting_is_read_back_from_the_file(self):
        pub = self.publisher()
        with open(pub.path, "w", encoding="utf-8") as handle:
            json.dump({"main_ha_version": "2026.4", "discovery_enabled": True}, handle)
        self.assertEqual(pub._load().main_ha_version, "2026.4")

    def test_the_setting_is_offered_to_the_ui(self):
        pub = self.publisher()
        self.assertIn("main_ha_version", pub.public_config())


class PageTest(unittest.TestCase):
    """The MQTT page carries the field with the other discovery settings."""

    ROOT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "custom_components", "integration_manager")

    def read(self, *parts):
        with open(os.path.join(self.ROOT, *parts), encoding="utf-8") as handle:
            return handle.read()

    def test_the_form_has_the_input_and_says_what_it_is_for(self):
        html = self.read("templates", "mqtt.html")
        self.assertIn('id="mq_main_ha_version"', html)
        label = [line for line in html.splitlines() if 'id="mq_main_ha_version"' in line][0]
        self.assertIn("title=", label)
        self.assertIn("consumes this discovery", label)

    def test_the_script_loads_and_saves_it_as_a_text_setting(self):
        js = self.read("static", "mqtt.js")
        self.assertIn("'main_ha_version'", js)
        self.assertIn("MQ_TEXT", js.split("'main_ha_version'")[0].rsplit("const ", 1)[-1])

    def test_the_page_shows_the_counters(self):
        js = self.read("static", "mqtt.js")
        self.assertIn("discovery_compat_device_classes_dropped", js)
        self.assertIn("discovery_compat_platforms_mirrored", js)


if __name__ == "__main__":
    unittest.main()
